# Generated by Django 5.2 on 2025-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_tag_order_notes_product_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
