# Generated by Django 5.2 on 2025-05-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
